// Generated by CoffeeScript 1.10.0
(function() {
  var PORT, PROMPT, colour, console_out, io, readline, rl, socket, username;

  PORT = 3000;

  readline = require('readline');

  rl = readline.createInterface(process.stdin, process.stdout);

  io = require('socket.io-client');

  colour = require('ansi-color').set;

  PROMPT = 'MSG > ';

  rl.setPrompt(PROMPT, PROMPT.length);

  socket = io("http://localhost:" + PORT);

  socket.on('message', function(msg) {
    var leader;
    if (msg.type === 'chat' && msg.user !== username) {
      leader = colour("<" + msg.user + ">", 'green');
      return console_out(leader + " " + msg.message);
    } else if (msg.type === 'notice') {
      return console_out(colour(msg.message, 'cyan'));
    }
  });

  username = null;

  rl.question('Nome de usuário: ', function(answer) {
    var msg;
    if (answer.trim() !== '') {
      username = answer;
      msg = username + " entrou no chat!";
      socket.emit('send', {
        type: 'notice',
        message: msg
      });
      return rl.prompt(true);
    }
  });

  rl.prompt();

  rl.on('line', function(msg) {
    socket.emit('send', {
      type: 'chat',
      message: msg,
      user: username
    });
    return rl.prompt(true);
  }).on('close', function() {
    console_out('Saindo do chat...');
    socket.emit('send', {
      type: 'exit',
      user: username
    });
    rl.prompt(false);
    return process.exit(0);
  });

  console_out = function(msg) {
    process.stdout.clearLine();
    process.stdout.cursorTo(0);
    console.log(msg);
    return rl.prompt(true);
  };

}).call(this);

//# sourceMappingURL=client.js.map
