// Generated by CoffeeScript 1.10.0
(function() {
  var PORT, io, users;

  PORT = 3000;

  io = require('socket.io')(PORT);

  users = [];

  io.on('connect', function(socket) {
    console.log('Usuário conectado');
    socket.on('send', function(msg) {
      if (msg.type === 'user') {
        if (users(indexOf(msg.username < 0))) {
          users.push(msg.username);
        }
      }
      if (msg.type === 'exit') {
        users.splice(users.indexOf(msg.username), 1);
      }
      return io.emit('message', msg);
    });
    return socket.on('disconnect', function() {
      return console.log('Usuário desconectado');
    });
  });

  console.log("Escutando na porta " + PORT + "...");

}).call(this);

//# sourceMappingURL=server.js.map
